import { productSchema, type Product } from "@/lib/schema";

const blurPlaceholder =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z/C/HwAFhAIKpGZo8QAAAABJRU5ErkJggg==";

const moncoutant = {
  city: "Moncoutant",
  dept: "Deux-Sèvres",
  lat: 46.6479,
  lng: -0.6342,
} as const;

const rawProducts: Product[] = [
  {
    slug: "brasero-signature-80",
    name: "Braséro Atelier LBF en Acier",
    category: "brasero",
    price: 890,
    shortDescription: "La pièce maîtresse pour les grandes tablées en extérieur.",
    description:
      "Le Braséro Signature 80 est notre modèle phare, conçu pour accueillir jusqu'à 10-12 convives autour d'un foyer généreux de 80 cm de diamètre. Fabriqué en acier corten HLE de 4 mm d'épaisseur dans notre atelier de Moncoutant, ce braséro allie robustesse et élégance intemporelle. Le bol de 5 mm offre une excellente inertie thermique pour maintenir des braises constantes pendant vos soirées. L'acier corten développe naturellement une patine protectrice qui le rend résistant aux intempéries et lui confère son caractère unique. Avec ses 48 kg et une hauteur de 42 cm, il garantit une stabilité parfaite et une diffusion homogène de la chaleur. Idéal pour cuisiner à la plancha, griller ou simplement profiter de la chaleur rayonnante, ce braséro devient le cœur vivant de votre jardin. Garantie 5 ans structure, fabrication française.",
    madeIn: "France",
    material: "Acier corten HLE",
    diameter: 80,
    thickness: 4,
    height: 42,
    weight: 48,
    warranty: "Garantie 5 ans structure",
    availability: "Expédition sous 7 jours ouvrés",
    shipping: "Livraison suivie partout en France métropolitaine",
    popularScore: 95,
    badge: "Best-seller atelier",
    specs: {
      acier: "Corten HLE 4 mm",
      epaisseur: "Bol 5 mm",
      dimensions: "Ø 60 cm x H 42 cm",
      poids: "48 kg",
    },
    highlights: [
      "Résiste naturellement à la corrosion",
      "Bord chanfreiné sécurisant",
      "Vasque soudée à la main",
    ],
    features: [
      {
        icon: "Flame",
        title: "Diffusion homogène",
        description: "Bord incliné pour une restitution douce de la chaleur.",
      },
      {
        icon: "ShieldCheck",
        title: "Acier certifié",
        description: "Traçabilité complète de nos plaques corten européennes.",
      },
      {
        icon: "Leaf",
        title: "Usages responsables",
        description: "Compatible cuisson plancha et bois issu de forêts locales.",
      },
    ],
    images: [
      {
        src: "/brasero4.png",
        alt: "Braséro Signature 80 en situation nocturne",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
      {
        src: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80",
        alt: "Détail d'acier corten braséro",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
      {
        src: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1200&q=80",
        alt: "Moment convivial autour du feu",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
    ],
    location: moncoutant,
    faq: [
      {
        question: "Comment entretenir l'acier corten ?",
        answer:
          "Une fine couche de rouille protectrice se forme naturellement. Évitez simplement l'eau stagnante et brossez légèrement chaque saison.",
      },
      {
        question: "Peut-on cuisiner directement dessus ?",
        answer:
          "Oui, il suffit d'ajouter notre anneau plancha (option) ou une grille en inox. L'acier corten supporte des températures élevées.",
      },
      {
        question: "Quelle quantité de bois prévoir ?",
        answer:
          "Un rechargement toutes les 45 minutes avec des bûches de 33 cm suffit pour maintenir un foyer généreux.",
      },
    ],
  },
  {
    slug: "brasero-horizon-60",
    name: "Braséro Atelier LBF en Acier",
    category: "brasero",
    price: 590,
    shortDescription: "Compact et léger, idéal pour les terrasses urbaines.",
    description:
      "Le Braséro Horizon 60 est parfaitement adapté aux espaces urbains et aux terrasses de taille moyenne. Avec son diamètre de 60 cm, il peut accueillir confortablement 6 à 8 personnes autour d'un feu chaleureux. Fabriqué en acier corten HLE de 3 mm d'épaisseur avec un bol de 5 mm, il offre un excellent compromis entre légèreté (32 kg) et durabilité. Son design épuré avec pied tulipe ventilé assure une circulation d'air optimale pour une combustion propre tout en protégeant votre sol des traces de chaleur. À 38 cm de hauteur, il permet une position confortable pour cuisiner ou se réchauffer. L'acier corten développe sa patine protectrice naturelle qui résiste aux années. Compatible avec notre anneau plancha de 58 cm, il transforme vos soirées en véritables moments gastronomiques. Disponible immédiatement avec livraison express sous 72h. Garantie 3 ans structure, fabrication française à Moncoutant.",
    madeIn: "France",
    material: "Acier corten HLE",
    diameter: 60,
    thickness: 3,
    height: 38,
    weight: 32,
    warranty: "Garantie 3 ans structure",
    availability: "Disponible immédiatement",
    shipping: "Livraison Express sous 72h",
    popularScore: 82,
    badge: "Edition terrasse",
    specs: {
      acier: "Corten HLE 3 mm",
      epaisseur: "Bol 5 mm",
      dimensions: "Ø 75 cm x H 38 cm",
      poids: "32 kg",
      compatibilite: "Anneau plancha 58 cm",
    },
    highlights: [
      "Pied ventilé anti-traces",
      "Idéal pour 6 à 8 convives",
      "Accessoire plancha disponible",
    ],
    features: [
      {
        icon: "Wind",
        title: "Tirage maîtrisé",
        description: "Grilles d'aération découpées au laser pour une combustion propre.",
      },
      {
        icon: "Sun",
        title: "Finition satinée",
        description: "Patine stabilisée en atelier pour un rendu uniforme.",
      },
      {
        icon: "Wrench",
        title: "Montage instantané",
        description: "Reçu soudé, aucun assemblage requis.",
      },
    ],
    images: [
      {
        src: "/Brasero.png",
        alt: "Braséro Horizon 60 sur un rooftop urbain",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
      {
        src: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=1200&q=80",
        alt: "Détail du pied ventilé du braséro",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
    ],
    location: moncoutant,
    faq: [
      {
        question: "Convient-il aux petits espaces ?",
        answer:
          "Oui, avec 60 cm de diamètre et un poids contenu il se déplace aisément et respecte les balcons grâce à son pied ventilé.",
      },
      {
        question: "Quelle est la durée de chauffe moyenne ?",
        answer:
          "Comptez 30 minutes pour atteindre la pleine braise, puis un ajout de deux bûches toutes les 40 minutes.",
      },
      {
        question: "Quel accessoire recommandez-vous ?",
        answer:
          "L'anneau plancha 58 cm pour saisir légumes et pièces de viande tout autour de la flamme.",
      },
    ],
  },
  {
    slug: "brasero-origine-100",
    name: "Braséro Atelier LBF en Acier",
    category: "brasero",
    price: 1290,
    shortDescription: "Format spectaculaire pour les événements et tables XL.",
    description:
      "Le Braséro Origine 100 représente notre modèle le plus imposant et spectaculaire, conçu pour les grandes réceptions et les passionnés de cuisine au feu de bois. Son diamètre impressionnant de 100 cm permet d'accueillir 12 à 16 convives et offre une surface de cuisson XXL. Forgé en acier corten premium de 5 mm d'épaisseur avec un bol massif de 5 mm, ce braséro de 62 kg garantit une stabilité absolue et une rétention thermique exceptionnelle. La rigole périphérique canalise les jus de cuisson, parfait pour les grillades et la cuisson plancha. À 45 cm de hauteur, il permet de cuisiner confortablement debout. Souvent choisi par les professionnels (gîtes, restaurants, événementiel), il résiste à une utilisation intensive. Compatible avec l'anneau plancha 95 cm et tous nos accessoires gastronomiques. Chaque pièce est numérotée et contrôlée individuellement dans notre atelier. Fabrication sur commande en 2 semaines, livraison palette sur RDV. Garantie 5 ans, made in France.",
    madeIn: "France",
    material: "Acier corten premium",
    diameter: 100,
    thickness: 5,
    height: 45,
    weight: 62,
    warranty: "Garantie 5 ans structure",
    availability: "Fabrication à la commande (2 semaines)",
    shipping: "Livraison palette sur RDV",
    popularScore: 78,
    badge: "Format pro",
    specs: {
      acier: "Corten premium 5 mm",
      epaisseur: "Bol 5 mm",
      dimensions: "Ø 90 cm x H 45 cm",
      poids: "62 kg",
      compatibilite: "Anneau plancha 95 cm",
    },
    highlights: [
      "Rigole anti-retombées",
      "Haute inertie thermique",
      "Planche à découper intégrée (option)",
    ],
    features: [
      {
        icon: "Sparkles",
        title: "Lignes sculpturales",
        description: "Bord biseauté pour sublimer la flamme sur 360°.",
      },
      {
        icon: "ChefHat",
        title: "Pensé pour cuisiner",
        description: "Compatible grille inox XXL et accessoires gastronomiques.",
      },
      {
        icon: "Factory",
        title: "Atelier Moncoutant",
        description: "Assemblé et contrôlé à la main, chaque pièce est numérotée.",
      },
    ],
    images: [
      {
        src: "https://images.unsplash.com/photo-1500534310685-79d0e5230d1d?auto=format&fit=crop&w=1200&q=80",
        alt: "Braséro Origine 100 prêt pour une grande tablée",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
      {
        src: "https://images.unsplash.com/photo-1449247709967-d4461a6a6103?auto=format&fit=crop&w=1200&q=80",
        alt: "Service plancha sur grand braséro",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
      {
        src: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
        alt: "Détail acier corten patiné",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
    ],
    location: moncoutant,
    faq: [
      {
        question: "Peut-on l'encastrer ?",
        answer:
          "Oui, Origine 100 peut être semi-encastré dans une terrasse en prévoyant une dalle béton 70x70 cm ventilée.",
      },
      {
        question: "Quel est le délai réel ?",
        answer:
          "Deux semaines fabrication + livraison palette sur créneau confirmé avec notre transporteur premium.",
      },
      {
        question: "Fournissez-vous une couverture ?",
        answer:
          "Une plaque d'acier galvanisé est proposée en option pour protéger la vasque lorsqu'elle n'est pas utilisée.",
      },
    ],
  },
  {
    slug: "brasero-compact-55",
    name: "Braséro Atelier LBF en Acier",
    category: "brasero",
    price: 420,
    shortDescription: "Le compagnon des balcons et petites terrasses.",
    description:
      "Le Braséro Compact 55 est spécialement conçu pour les petits espaces extérieurs, balcons et terrasses urbaines. Avec ses 55 cm de diamètre et seulement 24 kg, il reste facilement maniable tout en offrant la qualité de fabrication Brasero Atelier. Idéal pour 4 à 6 convives, il crée une ambiance chaleureuse sans encombrer votre espace. Fabriqué en acier brut thermolaqué de 3 mm avec un bol de 5 mm, il résiste aux intempéries et conserve son aspect élégant. Sa hauteur de 35 cm le rend parfait pour des assises basses ou des tabourets. Les pieds réglables assurent une parfaite stabilité sur tous les sols. Le capot anti-pluie inclus protège votre braséro entre chaque utilisation. Les poignées latérales discrètes permettent de le déplacer facilement une fois refroidi. Compatible avec la grille inox 50 cm pour vos grillades. En stock et expédié sous 4 à 5 jours. Garantie 2 ans structure, fabrication française à Moncoutant.",
    madeIn: "France",
    material: "Acier brut thermolaqué",
    diameter: 55,
    thickness: 3,
    height: 35,
    weight: 24,
    warranty: "Garantie 2 ans structure",
    availability: "En stock",
    shipping: "Livraison standard 4 à 5 jours",
    popularScore: 70,
    badge: "Nouveauté",
    specs: {
      acier: "Acier brut thermolaqué",
      epaisseur: "Bol 5 mm",
      dimensions: "Ø 105 cm x H 35 cm",
      poids: "24 kg",
      compatibilite: "Grille inox 50 cm",
    },
    highlights: [
      "Dessous ventilé",
      "Capot anti-pluie inclus",
      "Pieds réglables",
    ],
    features: [
      {
        icon: "Feather",
        title: "Ultra maniable",
        description: "Poignées discrètes intégrées pour le déplacer à froid.",
      },
      {
        icon: "Droplet",
        title: "Protection pluie",
        description: "Capot assorti fourni pour préserver la cuve.",
      },
      {
        icon: "Target",
        title: "Chaleur concentrée",
        description: "Vasque plus profonde pour un feu vif et rapide.",
      },
    ],
    images: [
      {
        src: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80",
        alt: "Braséro Compact 55 prêt à accueillir des invités",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
      {
        src: "https://images.unsplash.com/photo-1449247709967-d4461a6a6103?auto=format&fit=crop&w=1200&q=80",
        alt: "Détail poignée braséro",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
      {
        src: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1200&q=80",
        alt: "Feu de bois sur balcon",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
    ],
    location: moncoutant,
    faq: [
      {
        question: "Quelle surface minimale recommandez-vous ?",
        answer:
          "Un espace extérieur ventilé de 6 m² suffit, en respectant la réglementation locale de votre copropriété.",
      },
      {
        question: "Peut-on utiliser du charbon ?",
        answer:
          "Oui, l'acier thermolaqué résiste à la montée en température mais évitez l'alcool à brûler.",
      },
      {
        question: "Comment le stocker ?",
        answer:
          "Utilisez le capot fourni et, si possible, abritez-le sous un auvent pendant l'hiver.",
      },
    ],
  },
  {
    slug: "brasero-canyon-70",
    name: "Braséro Atelier LBF en Acier",
    category: "brasero",
    price: 760,
    shortDescription: "Silhouette sculpturale et large rebord pour jouer avec les braises.",
    description:
      "Le Braséro Canyon 70 incarne l'équilibre parfait entre performance et design sculptural. Son diamètre de 70 cm accueille confortablement 8 à 10 personnes autour d'un foyer généreux. Fabriqué en acier corten patiné de 4 mm avec un bol de 5 mm, il pèse 40 kg pour une stabilité optimale. Sa forme conique distinctive favorise un tirage naturel et une combustion efficace. Le plateau inférieur intégré, démontable par deux vis moletées, permet de ranger vos bûches à portée de main tout en participant à l'esthétique épurée de l'ensemble. À 40 cm de hauteur, il offre un confort d'utilisation idéal. Le drainage central invisible évacue l'eau de pluie sans laisser de traces sur votre terrasse. Le rebord incliné diffuse la chaleur harmonieusement vers les convives. Compatible avec la plancha 68 cm pour transformer vos repas en expériences gastronomiques. Assemblé sur demande en 10 jours avec livraison premium. Garantie 4 ans structure, édition jardin, fabrication française.",
    madeIn: "France",
    material: "Acier corten patiné",
    diameter: 70,
    thickness: 4,
    height: 40,
    weight: 40,
    warranty: "Garantie 4 ans structure",
    availability: "Assemblé à la demande (10 jours)",
    shipping: "Livraison premium avec prise de rendez-vous",
    popularScore: 76,
    badge: "Édition jardin",
    specs: {
      acier: "Corten patiné 4 mm",
      epaisseur: "Bol 5 mm",
      dimensions: "Ø 60 cm x H 40 cm",
      poids: "40 kg",
      compatibilite: "Plancha 68 cm",
    },
    highlights: [
      "Plateau bois intégré",
      "Ligne conique graphique",
      "Drainage central invisible",
    ],
    features: [
      {
        icon: "Droplet",
        title: "Drainage discret",
        description: "Soudure cachée au centre pour évacuer l'eau sans marquer la terrasse.",
      },
      {
        icon: "Layers",
        title: "Double plateau",
        description: "Rangez bûches et accessoires sur l'étage inférieur découpé au laser.",
      },
      {
        icon: "Compass",
        title: "Design radial",
        description: "Rebord incliné qui diffuse la chaleur doucement vers les convives.",
      },
    ],
    images: [
      {
        src: "https://images.unsplash.com/photo-1497215842964-222b430dc094?auto=format&fit=crop&w=1200&q=80",
        alt: "Braséro Canyon 70 illuminant un jardin paysagé",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
      {
        src: "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1200&q=80",
        alt: "Détail du rebord corten",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
      {
        src: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80",
        alt: "Braséro Canyon 70 au coucher du soleil",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
    ],
    location: moncoutant,
    faq: [
      {
        question: "Peut-on retirer le plateau inférieur ?",
        answer:
          "Oui, il est boulonné pour faciliter le nettoyage ou alléger l'ensemble lors du transport.",
      },
      {
        question: "La patine corten tache-t-elle ?",
        answer:
          "Nous stabilisons chaque pièce avant expédition. Un tapis en fibre de coco suffit si vous avez un bois très clair.",
      },
      {
        question: "Quel combustible privilégier ?",
        answer:
          "Des bûches de 25 à 30 cm permettent d'alimenter régulièrement le foyer sans dépasser du rebord.",
      },
    ],
  },
  {
    slug: "brasero-nomade-45",
    name: "Braséro Atelier LBF en Acier",
    category: "brasero",
    price: 320,
    shortDescription: "Format léger avec poignée intégrée pour suivre vos escapades.",
    description:
      "Le Braséro Nomade 45 révolutionne l'expérience du feu de camp en offrant un véritable braséro transportable. Avec ses 45 cm de diamètre et seulement 16 kg, il se glisse facilement dans votre coffre grâce à ses pieds rabattables et son sac de transport en toile waxée inclus. Idéal pour 4 convives, il crée une ambiance chaleureuse lors de vos escapades, pique-niques ou soirées plage. Fabriqué en acier galvanisé thermolaqué de 3 mm avec un bol de 5 mm, sa construction double peau innovante isole la chaleur et protège les surfaces sensibles (sable, herbe, terrasse bois). Hauteur de 28 cm seulement pour un transport optimisé. La poignée ceinture intégrée facilite le déplacement. Montage express en deux vis papillon pour le croisillon central. Compatible avec la grille pliable 42 cm fournie en option. Parfait pour le bois comme pour le charbon. Expédié sous 48h en point relais ou à domicile. Garantie 2 ans structure, fabrication française nomade.",
    madeIn: "France",
    material: "Acier galvanisé thermolaqué",
    diameter: 45,
    thickness: 3,
    height: 28,
    weight: 16,
    warranty: "Garantie 2 ans structure",
    availability: "Expédié sous 48h",
    shipping: "Livraison express en point relais ou domicile",
    popularScore: 68,
    badge: "Nomade",
    specs: {
      acier: "Galva thermolaqué 3 mm",
      epaisseur: "Bol 5 mm",
      dimensions: "Ø 75 cm x H 28 cm",
      poids: "16 kg",
      compatibilite: "Grille pliable 42 cm",
    },
    highlights: [
      "Poignée ceinture",
      "Pieds repliables",
      "Sac de transport inclus",
    ],
    features: [
      {
        icon: "Suitcase",
        title: "Ultra portable",
        description: "Pieds rabattables et housse toile waxée pour protéger l'acier.",
      },
      {
        icon: "Thermometer",
        title: "Double peau isolante",
        description: "Préserve les revêtements fragiles et limite les traces au sol.",
      },
      {
        icon: "Bolt",
        title: "Montage express",
        description: "Deux vis papillon suffisent pour verrouiller le croisillon central.",
      },
    ],
    images: [
      {
        src: "https://images.unsplash.com/photo-1523419409543-0c1df022bddb?auto=format&fit=crop&w=1200&q=80",
        alt: "Braséro Nomade 45 prêt pour une escapade",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
      {
        src: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80",
        alt: "Transport du braséro Nomade dans son sac",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
      {
        src: "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1200&q=80",
        alt: "Détail de la poignée ceinture",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
    ],
    location: moncoutant,
    faq: [
      {
        question: "Convient-il aux plages ?",
        answer:
          "Oui, la double peau isole du sable chaud. Rincez simplement la cuve après usage pour retirer le sel.",
      },
      {
        question: "Peut-on utiliser du charbon de bois ?",
        answer:
          "Oui, mais préférez un mélange bois + charbon pour préserver la montée en température homogène.",
      },
      {
        question: "Comment nettoyer la housse ?",
        answer:
          "Elle se lave à l'eau savonneuse tiède, puis laissez sécher à l'air libre avant de replier les pieds.",
      },
    ],
  },
  {
    slug: "brasero-atlas-90",
    name: "Braséro Atelier LBF en Acier",
    category: "brasero",
    price: 990,
    shortDescription: "Un disque monumental avec plateau log pour scenographier vos repas.",
    description:
      "Le Braséro Atlas 90 est une pièce monumentale conçue pour devenir l'élément sculptural central de votre jardin. Son diamètre de 90 cm accueille 10 à 14 convives autour de flammes spectaculaires. Pesant 55 kg et fabriqué en acier corten laminé de 4 mm avec un bol de 5 mm, il est conçu pour rester en extérieur toute l'année et développer sa patine unique. Sa structure en H intègre un plateau log qui transforme le rangement des bûches en élément décoratif. La lèvre interne double crée deux couronnes de chaleur concentriques, idéales pour la cuisson lente et maîtrisée. À 44 cm de hauteur, il offre un confort optimal debout. Les renforts invisibles sous la vasque supportent les charges lourdes et l'usage intensif. Résiste aux embruns marins. Le plateau se retire via deux vis moletées pour nettoyage saisonnier. Compatible anneau plancha 86 cm. Délai atelier 10 jours, livraison palette sur RDV. Garantie 5 ans structure, édition signature, made in France.",
    madeIn: "France",
    material: "Acier corten laminé",
    diameter: 90,
    thickness: 4,
    height: 44,
    weight: 55,
    warranty: "Garantie 5 ans structure",
    availability: "Délai atelier 10 jours",
    shipping: "Livraison palette sur rendez-vous",
    popularScore: 88,
    badge: "Edition signature",
    specs: {
      acier: "Corten laminé 4 mm",
      epaisseur: "Bol 5 mm",
      dimensions: "Ø 90 cm x H 44 cm",
      poids: "55 kg",
      compatibilite: "Anneau plancha 86 cm",
    },
    highlights: [
      "Anneau double feu",
      "Plateau log intégré",
      "Résiste aux embruns marins",
    ],
    features: [
      {
        icon: "ShieldCheck",
        title: "Structure blindée",
        description: "Renforts invisibles sous la vasque pour encaisser les charges lourdes.",
      },
      {
        icon: "Flame",
        title: "Lèvres concentriques",
        description: "La chaleur se répartit en deux couronnes parfaites pour la cuisson lente.",
      },
      {
        icon: "Layers",
        title: "Socle technique",
        description: "Rangements ventilés pour stocker des bûches sèches à portée de main.",
      },
    ],
    images: [
      {
        src: "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=80",
        alt: "Braséro Atlas 90 avec son socle log design",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
      {
        src: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1200&q=80",
        alt: "Zoom sur l'acier corten patiné du Braséro Atlas",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
      {
        src: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=1200&q=80",
        alt: "Plateau log rempli autour du feu",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
    ],
    location: moncoutant,
    faq: [
      {
        question: "Peut-il rester dehors toute l'année ?",
        answer:
          "Oui, l'acier corten se stabilise naturellement. Évacuez simplement les cendres pour préserver la vasque.",
      },
      {
        question: "Quel bois privilégier ?",
        answer:
          "Des bûches de 33 cm bien sèches offrent la combustion la plus régulière pour alimenter les deux couronnes.",
      },
      {
        question: "Comment nettoyer le plateau inférieur ?",
        answer:
          "Il se retire grâce à deux vis moletées pour permettre un dépoussiérage complet une fois par saison.",
      },
    ],
  },
  {
    slug: "brasero-zenith-50",
    name: "Braséro Atelier LBF en Acier",
    category: "brasero",
    price: 370,
    shortDescription: "Une capsule compacte avec anneau lumineux intégré.",
    description:
      "Le Braséro Zénith 50 combine innovation et design avec son système d'éclairage LED intégré unique. Son diamètre de 50 cm accueille 4 à 6 personnes autour d'un foyer intime. Avec seulement 20 kg, ce braséro en acier inox thermolaqué de 3 mm avec bol de 5 mm reste facilement maniable grâce à ses poignées intégrées. À 32 cm de hauteur, il s'adapte parfaitement aux balcons et petites terrasses. La base ajourée dissimule un anneau LED rechargeable USB-C offrant jusqu'à 12h d'autonomie avec intensité réglable. Cet éclairage d'ambiance transforme vos soirées en créant un halo lumineux autour des flammes. La finition satinée texturée résiste aux traces. La double paroi isole l'éclairage de la chaleur du foyer. Compatible grille inox 48 cm. L'interrupteur discret permet d'activer l'éclairage à volonté. Les pieds isolants protègent les surfaces sensibles. Expédié sous 72h. Garantie 2 ans structure. Compact lumineux, fabrication française.",
    madeIn: "France",
    material: "Acier inox thermolaqué",
    diameter: 50,
    thickness: 3,
    height: 32,
    weight: 20,
    warranty: "Garantie 2 ans structure",
    availability: "Expédié sous 72h",
    shipping: "Livraison standard partout en France",
    popularScore: 64,
    badge: "Compact lumineux",
    specs: {
      acier: "Inox thermolaqué 3 mm",
      epaisseur: "Bol 5 mm",
      dimensions: "Ø 105 cm x H 32 cm",
      poids: "20 kg",
      compatibilite: "Grille inox 48 cm",
    },
    highlights: [
      "Base éclairée",
      "Poignées intégrées",
      "Recharge USB-C",
    ],
    features: [
      {
        icon: "Battery",
        title: "LED autonome",
        description: "Jusqu'à 12 h d'ambiance lumineuse avec intensité réglable.",
      },
      {
        icon: "Feather",
        title: "Ultra léger",
        description: "20 kg seulement pour changer d'emplacement facilement.",
      },
      {
        icon: "Sun",
        title: "Finition satinée",
        description: "Thermolaquage texturé résistant aux traces de doigts.",
      },
    ],
    images: [
      {
        src: "https://images.unsplash.com/photo-1437623889155-075d40e2e59f?auto=format&fit=crop&w=1200&q=80",
        alt: "Braséro Zénith 50 avec anneau lumineux",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
      {
        src: "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1200&q=80",
        alt: "Détail de l'anneau lumineux du Zénith 50",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
    ],
    location: moncoutant,
    faq: [
      {
        question: "La LED supporte-t-elle la chaleur ?",
        answer:
          "Oui, l'éclairage est isolé par une double paroi et reste froid. Il se recharge via USB-C.",
      },
      {
        question: "Peut-on couper la lumière ?",
        answer:
          "Bien sûr, l'interrupteur discret à l'arrière permet de l'allumer uniquement quand vous le souhaitez.",
      },
      {
        question: "Convient-il aux balcons ?",
        answer:
          "Avec son diamètre de 50 cm et ses pieds isolants, il respecte les surfaces sensibles.",
      },
    ],
  },
  {
    slug: "brasero-dune-75",
    name: "Braséro Atelier LBF en Acier",
    category: "brasero",
    price: 680,
    shortDescription: "Inspiration désertique avec courbes asymétriques.",
    description:
      "Le Braséro Dune 75 se distingue par son design asymétrique audacieux inspiré des paysages désertiques. Son diamètre de 75 cm accueille 8 à 10 convives autour de courbes organiques uniques. Fabriqué en acier corten patiné de 4 mm, il pèse 44 kg et culmine à 48 cm pour une présence affirmée. Sa forme asymétrique n'est pas qu'esthétique : elle canalise naturellement les braises vers le centre pour une combustion optimale. Le pare-étincelles discret affleurant protège des projections même par vent léger. La base pivotante innovante permet d'orienter la flamme vers vos invités grâce à trois points d'ancrage larges garantissant stabilité absolue. La cuve profonde convient particulièrement aux longues veillées. La patine corten évolue avec le temps pour un caractère unique. Compatible avec grille demi-lune fixable sur la lèvre haute. Plateau fourni pour éviter traces au sol. Assemblé et livré en 8 jours avec transport spécialisé. Garantie 4 ans structure, édition désert, fabrication française Moncoutant.",
    madeIn: "France",
    material: "Acier corten patiné",
    diameter: 75,
    thickness: 4,
    height: 48,
    weight: 44,
    warranty: "Garantie 4 ans structure",
    availability: "Assemblé puis livré en 8 jours",
    shipping: "Transport spécialisé avec suivi",
    popularScore: 74,
    badge: "Edition désert",
    specs: {
      acier: "Corten patiné 4 mm",
      epaisseur: "4 mm",
      dimensions: "Ø 75 cm x H 48 cm",
      poids: "44 kg",
      compatibilite: "Cloche coupe-vent 70 cm",
    },
    highlights: [
      "Cuve asymétrique",
      "Pare-étincelles intégré",
      "Base pivotante",
    ],
    features: [
      {
        icon: "Wind",
        title: "Pare-étincelles discret",
        description: "Lame inox affleurante qui canalise les projections même par vent léger.",
      },
      {
        icon: "Compass",
        title: "Base pivotante",
        description: "Tournez la Dune pour orienter la flamme vers vos convives.",
      },
      {
        icon: "Sparkles",
        title: "Patine évolutive",
        description: "Chaque pièce développe une teinte unique au fil des saisons.",
      },
    ],
    images: [
      {
        src: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
        alt: "Braséro Dune 75 dans un paysage désertique",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
      {
        src: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1200&q=80",
        alt: "Courbes asymétriques de la Dune 75",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
    ],
    location: moncoutant,
    faq: [
      {
        question: "Est-elle stable malgré la forme asymétrique ?",
        answer:
          "Oui, la base pivotante comporte trois points d'ancrage larges qui maintiennent l'ensemble.",
      },
      {
        question: "Peut-on ajouter une grille ?",
        answer:
          "Nous proposons une grille en demi-lune qui se fixe sur la lèvre la plus haute.",
      },
      {
        question: "La patine tache-t-elle ?",
        answer:
          "Comme tout corten, quelques pigments peuvent ruisseler les premiers mois. Utilisez le plateau fourni si nécessaire.",
      },
    ],
  },
  {
    slug: "brasero-lumina-65",
    name: "Braséro Atelier LBF en Acier",
    category: "brasero",
    price: 540,
    shortDescription: "Format vertical avec niches pour bougies et accessoires.",
    description:
      "Le Braséro Lumina 65 propose une expérience visuelle unique grâce à son fût perforé créant des jeux d'ombres et de lumière. Avec 65 cm de diamètre, il accueille 6 à 8 personnes dans une ambiance féérique. Pesant 36 kg et culminant à 70 cm de hauteur, ce braséro en acier brut verni de 3 mm transforme chaque soirée en spectacle lumineux. Les perforations coniques découpées au laser dans le fût créent une constellation de lumière qui se projette tout autour, doublant l'effet visuel des flammes. Les niches latérales intégrées restent tièdes grâce à la double cloison isolante et peuvent accueillir photophores, bougies ou accessoires. Le rebord anti-coulure canalise les jus de cuisson pour protéger la base. Compatible avec grille suspendue 60 cm pour cuisson en hauteur. Trois perçages discrets permettent fixation permanente au sol si désiré. Production 5 jours ouvrés avec tracking. Entretien simple au chiffon microfibre. Garantie 3 ans structure, édition illumination, fabrication française.",
    madeIn: "France",
    material: "Acier brut verni",
    diameter: 65,
    thickness: 3,
    height: 70,
    weight: 36,
    warranty: "Garantie 3 ans structure",
    availability: "Production 5 jours ouvrés",
    shipping: "Livraison standard avec tracking",
    popularScore: 71,
    badge: "Illumination",
    specs: {
      acier: "Acier brut verni 3 mm",
      epaisseur: "3 mm",
      dimensions: "Ø 65 cm x H 70 cm",
      poids: "36 kg",
      compatibilite: "Grille suspendue 60 cm",
    },
    highlights: [
      "Fût perforé lumineux",
      "Niches accessoires",
      "Rebord anti-coulure",
    ],
    features: [
      {
        icon: "Lightbulb",
        title: "Jeu d'ombres",
        description: "Perforations coniques créant une constellation tout autour du foyer.",
      },
      {
        icon: "Box",
        title: "Rangements latéraux",
        description: "Rangez allume-feu, bougies et verres dans les niches dédiées.",
      },
      {
        icon: "Droplet",
        title: "Rebord canalisation",
        description: "Un discret retour évacue les jus de cuisson et protège la base.",
      },
    ],
    images: [
      {
        src: "https://images.unsplash.com/photo-1500534313519-23966a77d8e1?auto=format&fit=crop&w=1200&q=80",
        alt: "Braséro Lumina 65 et ses niches lumineuses",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
      {
        src: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
        alt: "Détail des perforations lumineuses",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
    ],
    location: moncoutant,
    faq: [
      {
        question: "Les niches chauffent-elles ?",
        answer:
          "Elles restent tièdes grâce à une double cloison isolante, idéales pour les bougies ou accessoires.",
      },
      {
        question: "Peut-on fixer Lumina au sol ?",
        answer:
          "Oui, trois perçages sont dissimulés à la base pour une fixation permanente.",
      },
      {
        question: "Quel entretien prévoir ?",
        answer:
          "Essuyez le vernis avec un chiffon microfibre et graissez légèrement la vasque tous les débuts de saison.",
      },
    ],
  },
  {
    slug: "fendeur-buches-atelier",
    name: "Braséro Atelier LBF en Acier",
    category: "fendeur",
    price: 270,
    shortDescription: "Préparez vos bûches en toute sécurité, sans effort.",
    description:
      "Conçu pour accompagner nos braséros, ce fendeur manuel stabilise les bûches et multiplie votre force sans recourir à un outil motorisé. Acier 6 mm, lame trempée et anneaux de maintien garantissent une coupe précise.",
    madeIn: "France",
    material: "Acier brut thermolaqué",
    diameter: 0,
    thickness: 6,
    height: 62,
    weight: 18,
    warranty: "Garantie 3 ans",
    availability: "En stock",
    shipping: "Livraison suivie sous 4 jours",
    popularScore: 60,
    badge: "Atelier Moncoutant",
    specs: {
      acier: "Acier structuré 6 mm",
      epaisseur: "6 mm",
      dimensions: "H 62 cm x L 30 cm",
      poids: "18 kg",
      compatibilite: "Bûches jusqu'à 40 cm",
    },
    highlights: [
      "Sécurité accrue",
      "Aiguisage offert la première année",
      "Patins anti-vibrations",
    ],
    features: [
      {
        icon: "Axe",
        title: "Force démultipliée",
        description: "Bras de levier optimisé pour fendre sans effort excessif.",
      },
      {
        icon: "Shield",
        title: "Stabilité max",
        description: "Anneau de maintien empêchant la bûche de rebondir.",
      },
      {
        icon: "Box",
        title: "Transport facile",
        description: "Poignées latérales équilibrées pour le ranger après usage.",
      },
    ],
    images: [
      {
        src: "/acceuil/Fendeur-Buches.png",
        alt: "Fendeur à bûches",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
      {
        src: "https://images.unsplash.com/photo-1470246973918-29a93221c455?auto=format&fit=crop&w=1200&q=80",
        alt: "Détail de la lame trempée",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
      {
        src: "https://images.unsplash.com/photo-1449247709967-d4461a6a6103?auto=format&fit=crop&w=1200&q=80",
        alt: "Poignée de transport du fendeur",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
    ],
    location: moncoutant,
    faq: [
      {
        question: "Quels bois peut-on fendre ?",
        answer:
          "Tous les bois secs jusqu'à 40 cm de hauteur. Pour le chêne très noueux, réalisez deux passes.",
      },
      {
        question: "La lame peut-elle être remplacée ?",
        answer:
          "Oui, elle est démontable et nous proposons un kit de remplacement depuis l'atelier.",
      },
      {
        question: "Faut-il l'ancrer au sol ?",
        answer:
          "Ce n'est pas obligatoire mais des perçages sont prévus pour fixer l'outil sur un billot si besoin.",
      },
    ],
  },
  // ACCESSOIRES
  {
    slug: "plancha-acier-60",
    name: "Plancha Acier Ø60 cm",
    category: "accessoire",
    price: 189,
    shortDescription: "Plancha en acier pour braséro de 60 cm.",
    description: "Cette plancha en acier de 6 mm d'épaisseur s'adapte parfaitement aux braséros de 60 cm. Surface de cuisson généreuse pour grillades, légumes et fruits de mer. Développe un culottage naturel avec l'usage.",
    madeIn: "France",
    material: "Acier brut",
    diameter: 60,
    thickness: 6,
    height: 3,
    weight: 8,
    warranty: "Garantie 2 ans",
    availability: "En stock",
    shipping: "Livraison sous 5 jours",
    popularScore: 85,
    badge: "Accessoire",
    specs: { acier: "Acier brut 6 mm", epaisseur: "6 mm", dimensions: "Ø 60 cm", poids: "8 kg" },
    highlights: ["Compatible braséro Ø60", "Culottage naturel", "Fabrication française"],
    features: [{ icon: "Flame", title: "Cuisson parfaite", description: "Répartition homogène de la chaleur." }],
    images: [{ src: "/accessories/plancha-acier.jpg", alt: "Plancha acier", width: 1200, height: 900, blurDataURL: blurPlaceholder }],
    location: moncoutant,
    faq: [{ question: "Comment entretenir la plancha ?", answer: "Nettoyez à chaud avec une spatule, huilez légèrement après chaque usage." }],
  },
  {
    slug: "plancha-acier-80",
    name: "Plancha Acier Ø80 cm",
    category: "accessoire",
    price: 249,
    shortDescription: "Grande plancha pour braséro de 80 cm.",
    description: "Plancha XXL en acier de 6 mm pour les grandes tablées. Compatible avec les braséros de 80 cm de diamètre. Idéale pour cuisiner pour 10-12 personnes.",
    madeIn: "France",
    material: "Acier brut",
    diameter: 80,
    thickness: 6,
    height: 3,
    weight: 12,
    warranty: "Garantie 2 ans",
    availability: "En stock",
    shipping: "Livraison sous 5 jours",
    popularScore: 82,
    badge: "Accessoire",
    specs: { acier: "Acier brut 6 mm", epaisseur: "6 mm", dimensions: "Ø 80 cm", poids: "12 kg" },
    highlights: ["Compatible braséro Ø80", "Grande surface", "Fabrication française"],
    features: [{ icon: "Flame", title: "Surface XXL", description: "Cuisinez pour toute la famille." }],
    images: [{ src: "/accessories/plancha-acier.jpg", alt: "Plancha acier 80", width: 1200, height: 900, blurDataURL: blurPlaceholder }],
    location: moncoutant,
    faq: [{ question: "Peut-on la laisser dehors ?", answer: "Oui, mais huilez-la pour éviter la rouille." }],
  },
  {
    slug: "grille-inox-60",
    name: "Grille Inox Ø60 cm",
    category: "accessoire",
    price: 129,
    shortDescription: "Grille de cuisson en inox alimentaire.",
    description: "Grille en acier inoxydable 304 alimentaire, parfaite pour les grillades directes sur braséro. Barreaux de 8 mm espacés de 15 mm pour une cuisson optimale.",
    madeIn: "France",
    material: "Inox 304",
    diameter: 60,
    thickness: 8,
    height: 2,
    weight: 4,
    warranty: "Garantie 3 ans",
    availability: "En stock",
    shipping: "Livraison sous 3 jours",
    popularScore: 88,
    badge: "Best-seller",
    specs: { acier: "Inox 304", epaisseur: "8 mm", dimensions: "Ø 60 cm", poids: "4 kg" },
    highlights: ["Inox alimentaire", "Nettoyage facile", "Anti-rouille"],
    features: [{ icon: "ShieldCheck", title: "Hygiénique", description: "Inox alimentaire certifié." }],
    images: [{ src: "/accessories/grille-inox.jpg", alt: "Grille inox", width: 1200, height: 900, blurDataURL: blurPlaceholder }],
    location: moncoutant,
    faq: [{ question: "Passe-t-elle au lave-vaisselle ?", answer: "Oui, elle est compatible lave-vaisselle." }],
  },
  {
    slug: "grille-inox-80",
    name: "Grille Inox Ø80 cm",
    category: "accessoire",
    price: 169,
    shortDescription: "Grande grille inox pour braséro 80 cm.",
    description: "Grille XXL en inox 304 pour les braséros de 80 cm. Surface généreuse pour griller viandes, poissons et légumes simultanément.",
    madeIn: "France",
    material: "Inox 304",
    diameter: 80,
    thickness: 8,
    height: 2,
    weight: 6,
    warranty: "Garantie 3 ans",
    availability: "En stock",
    shipping: "Livraison sous 3 jours",
    popularScore: 84,
    badge: "Accessoire",
    specs: { acier: "Inox 304", epaisseur: "8 mm", dimensions: "Ø 80 cm", poids: "6 kg" },
    highlights: ["Grande surface", "Inox premium", "Durable"],
    features: [{ icon: "ShieldCheck", title: "Robuste", description: "Supporte les charges lourdes." }],
    images: [{ src: "/accessories/grille-inox.jpg", alt: "Grille inox 80", width: 1200, height: 900, blurDataURL: blurPlaceholder }],
    location: moncoutant,
    faq: [{ question: "Quel poids supporte-t-elle ?", answer: "Jusqu'à 25 kg sans problème." }],
  },
  {
    slug: "couvercle-acier-60",
    name: "Couvercle Acier Ø60 cm",
    category: "accessoire",
    price: 89,
    shortDescription: "Couvercle de protection pour braséro.",
    description: "Couvercle en acier galvanisé pour protéger votre braséro des intempéries. Poignée centrale en bois pour une manipulation facile.",
    madeIn: "France",
    material: "Acier galvanisé",
    diameter: 60,
    thickness: 2,
    height: 8,
    weight: 3,
    warranty: "Garantie 2 ans",
    availability: "En stock",
    shipping: "Livraison sous 3 jours",
    popularScore: 75,
    badge: "Protection",
    specs: { acier: "Galvanisé", epaisseur: "2 mm", dimensions: "Ø 60 cm", poids: "3 kg" },
    highlights: ["Protège de la pluie", "Poignée bois", "Léger"],
    features: [{ icon: "ShieldCheck", title: "Protection", description: "Garde votre braséro au sec." }],
    images: [{ src: "/accessories/couvercle-acier.jpg", alt: "Couvercle", width: 1200, height: 900, blurDataURL: blurPlaceholder }],
    location: moncoutant,
    faq: [{ question: "Résiste-t-il au vent ?", answer: "Oui, son poids le maintient en place." }],
  },
  {
    slug: "couvercle-acier-80",
    name: "Couvercle Acier Ø80 cm",
    category: "accessoire",
    price: 119,
    shortDescription: "Grand couvercle pour braséro 80 cm.",
    description: "Couvercle de protection en acier galvanisé pour les grands braséros. Indispensable pour prolonger la durée de vie de votre équipement.",
    madeIn: "France",
    material: "Acier galvanisé",
    diameter: 80,
    thickness: 2,
    height: 10,
    weight: 5,
    warranty: "Garantie 2 ans",
    availability: "En stock",
    shipping: "Livraison sous 3 jours",
    popularScore: 72,
    badge: "Protection",
    specs: { acier: "Galvanisé", epaisseur: "2 mm", dimensions: "Ø 80 cm", poids: "5 kg" },
    highlights: ["Protection optimale", "Robuste", "Poignée ergonomique"],
    features: [{ icon: "ShieldCheck", title: "Durabilité", description: "Prolonge la vie du braséro." }],
    images: [{ src: "/accessories/couvercle-acier.jpg", alt: "Couvercle 80", width: 1200, height: 900, blurDataURL: blurPlaceholder }],
    location: moncoutant,
    faq: [{ question: "Peut-on le personnaliser ?", answer: "Oui, gravure laser disponible sur demande." }],
  },
  {
    slug: "pince-brasero-inox",
    name: "Pince à Braises Inox 60 cm",
    category: "accessoire",
    price: 45,
    shortDescription: "Pince longue pour manipuler les braises.",
    description: "Pince professionnelle en inox de 60 cm pour manipuler bûches et braises en toute sécurité. Manche isolant en bois de hêtre.",
    madeIn: "France",
    material: "Inox / Bois",
    diameter: 0,
    thickness: 0,
    height: 60,
    weight: 0.8,
    warranty: "Garantie 2 ans",
    availability: "En stock",
    shipping: "Livraison sous 2 jours",
    popularScore: 90,
    badge: "Indispensable",
    specs: { acier: "Inox", epaisseur: "N/A", dimensions: "L 60 cm", poids: "0.8 kg" },
    highlights: ["Manche isolant", "Longueur sécuritaire", "Prise ferme"],
    features: [{ icon: "ShieldCheck", title: "Sécurité", description: "Manipulez sans vous brûler." }],
    images: [{ src: "/accessories/pince-brasero.jpg", alt: "Pince braises", width: 1200, height: 900, blurDataURL: blurPlaceholder }],
    location: moncoutant,
    faq: [{ question: "Le manche chauffe-t-il ?", answer: "Non, le bois de hêtre isole parfaitement." }],
  },
  {
    slug: "tisonnier-acier-70",
    name: "Tisonnier Acier 70 cm",
    category: "accessoire",
    price: 35,
    shortDescription: "Tisonnier pour attiser le feu.",
    description: "Tisonnier forgé à la main en acier massif. Pointe effilée pour réarranger les bûches et attiser les braises efficacement.",
    madeIn: "France",
    material: "Acier forgé",
    diameter: 0,
    thickness: 0,
    height: 70,
    weight: 1.2,
    warranty: "Garantie à vie",
    availability: "En stock",
    shipping: "Livraison sous 2 jours",
    popularScore: 78,
    badge: "Artisanal",
    specs: { acier: "Acier forgé", epaisseur: "N/A", dimensions: "L 70 cm", poids: "1.2 kg" },
    highlights: ["Forgé main", "Solide", "Prise en main agréable"],
    features: [{ icon: "Flame", title: "Efficace", description: "Attisez le feu facilement." }],
    images: [{ src: "/accessories/tisonnier.jpg", alt: "Tisonnier", width: 1200, height: 900, blurDataURL: blurPlaceholder }],
    location: moncoutant,
    faq: [{ question: "Est-il lourd ?", answer: "1.2 kg, équilibré pour une bonne prise en main." }],
  },
  {
    slug: "pelle-cendres-inox",
    name: "Pelle à Cendres Inox",
    category: "accessoire",
    price: 29,
    shortDescription: "Pelle pour nettoyer les cendres.",
    description: "Pelle en inox avec manche bois pour évacuer les cendres de votre braséro. Bords relevés pour éviter les débordements.",
    madeIn: "France",
    material: "Inox / Bois",
    diameter: 0,
    thickness: 0,
    height: 45,
    weight: 0.5,
    warranty: "Garantie 2 ans",
    availability: "En stock",
    shipping: "Livraison sous 2 jours",
    popularScore: 70,
    badge: "Pratique",
    specs: { acier: "Inox", epaisseur: "N/A", dimensions: "L 45 cm", poids: "0.5 kg" },
    highlights: ["Bords relevés", "Manche bois", "Facile à nettoyer"],
    features: [{ icon: "Leaf", title: "Entretien", description: "Nettoyez votre braséro facilement." }],
    images: [{ src: "/accessories/pelle-cendres.jpg", alt: "Pelle cendres", width: 1200, height: 900, blurDataURL: blurPlaceholder }],
    location: moncoutant,
    faq: [{ question: "Quelle contenance ?", answer: "Environ 0.5 litre de cendres par pelletée." }],
  },
  {
    slug: "gants-cuir-resistant",
    name: "Gants Cuir Résistant Chaleur",
    category: "accessoire",
    price: 49,
    shortDescription: "Gants de protection haute température.",
    description: "Gants en cuir de vachette doublé kevlar, résistants jusqu'à 500°C. Longueur 35 cm pour protéger les avant-bras.",
    madeIn: "France",
    material: "Cuir / Kevlar",
    diameter: 0,
    thickness: 0,
    height: 35,
    weight: 0.4,
    warranty: "Garantie 1 an",
    availability: "En stock",
    shipping: "Livraison sous 2 jours",
    popularScore: 92,
    badge: "Sécurité",
    specs: { acier: "N/A", epaisseur: "N/A", dimensions: "Taille unique", poids: "0.4 kg" },
    highlights: ["Résiste 500°C", "Cuir épais", "Confortable"],
    features: [{ icon: "ShieldCheck", title: "Protection max", description: "Manipulez en toute sécurité." }],
    images: [{ src: "/accessories/gants-cuir.jpg", alt: "Gants cuir", width: 1200, height: 900, blurDataURL: blurPlaceholder }],
    location: moncoutant,
    faq: [{ question: "Taille unique ?", answer: "Oui, convient à la plupart des mains." }],
  },
  {
    slug: "tablier-cuir-bbq",
    name: "Tablier Cuir BBQ",
    category: "accessoire",
    price: 79,
    shortDescription: "Tablier professionnel en cuir.",
    description: "Tablier en cuir véritable avec poches pour accessoires. Protection complète contre les projections et la chaleur.",
    madeIn: "France",
    material: "Cuir vachette",
    diameter: 0,
    thickness: 0,
    height: 90,
    weight: 1.5,
    warranty: "Garantie 2 ans",
    availability: "En stock",
    shipping: "Livraison sous 3 jours",
    popularScore: 75,
    badge: "Style",
    specs: { acier: "N/A", epaisseur: "N/A", dimensions: "90 x 60 cm", poids: "1.5 kg" },
    highlights: ["Cuir véritable", "Poches pratiques", "Look pro"],
    features: [{ icon: "ShieldCheck", title: "Protection", description: "Cuisinez sans tacher vos vêtements." }],
    images: [{ src: "/accessories/tablier-cuir.jpg", alt: "Tablier cuir", width: 1200, height: 900, blurDataURL: blurPlaceholder }],
    location: moncoutant,
    faq: [{ question: "Est-il lavable ?", answer: "Nettoyez au chiffon humide, pas de machine." }],
  },
  {
    slug: "support-buches-acier",
    name: "Support à Bûches Acier",
    category: "accessoire",
    price: 149,
    shortDescription: "Range-bûches design en acier.",
    description: "Support à bûches en acier corten assorti à votre braséro. Capacité 0.3 stère, ventilation optimale pour garder le bois sec.",
    madeIn: "France",
    material: "Acier corten",
    diameter: 0,
    thickness: 3,
    height: 100,
    weight: 25,
    warranty: "Garantie 5 ans",
    availability: "En stock",
    shipping: "Livraison sous 7 jours",
    popularScore: 80,
    badge: "Design",
    specs: { acier: "Corten 3 mm", epaisseur: "3 mm", dimensions: "L100 x P40 x H100 cm", poids: "25 kg" },
    highlights: ["Design assorti", "Bois ventilé", "Grande capacité"],
    features: [{ icon: "Box", title: "Rangement", description: "Gardez vos bûches à portée." }],
    images: [{ src: "/accessories/support-buches.jpg", alt: "Support bûches", width: 1200, height: 900, blurDataURL: blurPlaceholder }],
    location: moncoutant,
    faq: [{ question: "Combien de bûches ?", answer: "Environ 50 bûches de 33 cm." }],
  },
  {
    slug: "allume-feu-naturel",
    name: "Allume-feu Naturel (x50)",
    category: "accessoire",
    price: 19,
    shortDescription: "Allume-feu écologique en laine de bois.",
    description: "50 allume-feu 100% naturels en laine de bois et cire végétale. Combustion propre sans odeur chimique.",
    madeIn: "France",
    material: "Bois / Cire",
    diameter: 0,
    thickness: 0,
    height: 5,
    weight: 1,
    warranty: "N/A",
    availability: "En stock",
    shipping: "Livraison sous 2 jours",
    popularScore: 85,
    badge: "Écologique",
    specs: { acier: "N/A", epaisseur: "N/A", dimensions: "5 x 3 cm", poids: "1 kg (lot)" },
    highlights: ["100% naturel", "Sans odeur", "Longue combustion"],
    features: [{ icon: "Leaf", title: "Écolo", description: "Respectueux de l'environnement." }],
    images: [{ src: "/accessories/allume-feu.jpg", alt: "Allume-feu", width: 1200, height: 900, blurDataURL: blurPlaceholder }],
    location: moncoutant,
    faq: [{ question: "Durée de combustion ?", answer: "8 à 10 minutes par unité." }],
  },
  {
    slug: "brosse-nettoyage-laiton",
    name: "Brosse Nettoyage Laiton",
    category: "accessoire",
    price: 25,
    shortDescription: "Brosse pour nettoyer grilles et plancha.",
    description: "Brosse à poils laiton, idéale pour nettoyer les grilles et planchas sans les rayer. Manche bois ergonomique.",
    madeIn: "France",
    material: "Laiton / Bois",
    diameter: 0,
    thickness: 0,
    height: 30,
    weight: 0.3,
    warranty: "Garantie 1 an",
    availability: "En stock",
    shipping: "Livraison sous 2 jours",
    popularScore: 72,
    badge: "Entretien",
    specs: { acier: "N/A", epaisseur: "N/A", dimensions: "L 30 cm", poids: "0.3 kg" },
    highlights: ["Poils laiton", "Ne raye pas", "Manche ergonomique"],
    features: [{ icon: "Sparkles", title: "Nettoyage", description: "Grilles impeccables." }],
    images: [{ src: "/accessories/brosse-nettoyage.jpg", alt: "Brosse laiton", width: 1200, height: 900, blurDataURL: blurPlaceholder }],
    location: moncoutant,
    faq: [{ question: "Pour quels matériaux ?", answer: "Inox, acier, fonte." }],
  },
  {
    slug: "spatule-plancha-inox",
    name: "Spatule Plancha Inox XL",
    category: "accessoire",
    price: 35,
    shortDescription: "Grande spatule pour plancha.",
    description: "Spatule professionnelle en inox avec lame de 15 cm. Parfaite pour retourner et servir sur plancha.",
    madeIn: "France",
    material: "Inox / Bois",
    diameter: 0,
    thickness: 0,
    height: 40,
    weight: 0.4,
    warranty: "Garantie 2 ans",
    availability: "En stock",
    shipping: "Livraison sous 2 jours",
    popularScore: 82,
    badge: "Pro",
    specs: { acier: "Inox", epaisseur: "N/A", dimensions: "L 40 cm", poids: "0.4 kg" },
    highlights: ["Lame large", "Inox pro", "Manche bois"],
    features: [{ icon: "ChefHat", title: "Cuisine", description: "Comme un chef sur plancha." }],
    images: [{ src: "/accessories/spatule-plancha.png", alt: "Spatule plancha", width: 1200, height: 900, blurDataURL: blurPlaceholder }],
    location: moncoutant,
    faq: [{ question: "Lame flexible ?", answer: "Semi-rigide, idéale pour plancha." }],
    customSpecs: [
      { label: "Marque", value: "France Braseros" },
      { label: "Fabrication", value: "France" },
      { label: "Matière", value: "Inox / Bois" },
      { label: "Longueur", value: "40 cm" },
      { label: "Largeur lame", value: "15 cm" },
      { label: "Poids", value: "0.4 kg" },
      { label: "Usage", value: "Retourner et servir sur plancha" },
    ],
  },
  {
    slug: "kit-ustensiles-bbq",
    name: "Kit 5 Ustensiles BBQ",
    category: "accessoire",
    price: 89,
    shortDescription: "Set complet d'ustensiles barbecue.",
    description: "Kit comprenant pince, spatule, fourchette, brosse et couteau. Inox et manche bois, livré dans un étui de rangement.",
    madeIn: "France",
    material: "Inox / Bois",
    diameter: 0,
    thickness: 0,
    height: 45,
    weight: 2,
    warranty: "Garantie 2 ans",
    availability: "En stock",
    shipping: "Livraison sous 3 jours",
    popularScore: 88,
    badge: "Pack complet",
    specs: { acier: "Inox", epaisseur: "N/A", dimensions: "Étui 50 cm", poids: "2 kg" },
    highlights: ["5 ustensiles", "Étui inclus", "Qualité pro"],
    features: [{ icon: "Box", title: "Complet", description: "Tout pour cuisiner au feu." }],
    images: [{ src: "/accessories/kit-ustensiles.jpg", alt: "Kit ustensiles", width: 1200, height: 900, blurDataURL: blurPlaceholder }],
    location: moncoutant,
    faq: [{ question: "Contenu du kit ?", answer: "Pince, spatule, fourchette, brosse, couteau." }],
  },
  {
    slug: "seau-cendres-metal",
    name: "Seau à Cendres Métal 15L",
    category: "accessoire",
    price: 39,
    shortDescription: "Seau métallique pour cendres chaudes.",
    description: "Seau en acier galvanisé 15 litres avec couvercle hermétique. Peut recevoir des cendres encore chaudes en toute sécurité.",
    madeIn: "France",
    material: "Acier galvanisé",
    diameter: 30,
    thickness: 1,
    height: 35,
    weight: 2,
    warranty: "Garantie 2 ans",
    availability: "En stock",
    shipping: "Livraison sous 3 jours",
    popularScore: 70,
    badge: "Sécurité",
    specs: { acier: "Galvanisé", epaisseur: "1 mm", dimensions: "Ø30 x H35 cm", poids: "2 kg" },
    highlights: ["Cendres chaudes OK", "Couvercle hermétique", "15 litres"],
    features: [{ icon: "ShieldCheck", title: "Sécurisé", description: "Stockez les cendres sans risque." }],
    images: [{ src: "/accessories/seau-cendres.jpg", alt: "Seau cendres", width: 1200, height: 900, blurDataURL: blurPlaceholder }],
    location: moncoutant,
    faq: [{ question: "Résiste à quelle température ?", answer: "Jusqu'à 300°C sans problème." }],
  },
  {
    slug: "pare-etincelles-60",
    name: "Pare-étincelles Ø60 cm",
    category: "accessoire",
    price: 69,
    shortDescription: "Protection contre les projections.",
    description: "Grille pare-étincelles en acier inox, empêche les projections de braises. Indispensable près des zones sensibles.",
    madeIn: "France",
    material: "Inox",
    diameter: 60,
    thickness: 0,
    height: 15,
    weight: 2,
    warranty: "Garantie 2 ans",
    availability: "En stock",
    shipping: "Livraison sous 3 jours",
    popularScore: 76,
    badge: "Sécurité",
    specs: { acier: "Inox", epaisseur: "N/A", dimensions: "Ø 60 cm", poids: "2 kg" },
    highlights: ["Anti-projections", "Inox durable", "Facile à poser"],
    features: [{ icon: "ShieldCheck", title: "Protection", description: "Feu en toute sérénité." }],
    images: [{ src: "/accessories/pare-etincelles.jpg", alt: "Pare-étincelles", width: 1200, height: 900, blurDataURL: blurPlaceholder }],
    location: moncoutant,
    faq: [{ question: "Se pose comment ?", answer: "Simplement posé sur le braséro." }],
  },
  {
    slug: "thermometre-bbq-digital",
    name: "Thermomètre BBQ Digital",
    category: "accessoire",
    price: 45,
    shortDescription: "Thermomètre de cuisson précis.",
    description: "Thermomètre digital avec sonde inox, affichage instantané. Parfait pour maîtriser la cuisson de vos viandes.",
    madeIn: "France",
    material: "Inox / ABS",
    diameter: 0,
    thickness: 0,
    height: 25,
    weight: 0.15,
    warranty: "Garantie 1 an",
    availability: "En stock",
    shipping: "Livraison sous 2 jours",
    popularScore: 80,
    badge: "Précision",
    specs: { acier: "Sonde inox", epaisseur: "N/A", dimensions: "L 25 cm", poids: "0.15 kg" },
    highlights: ["Lecture instantanée", "Précis ±1°C", "Sonde longue"],
    features: [{ icon: "Target", title: "Précision", description: "Cuisson parfaite à chaque fois." }],
    images: [{ src: "/accessories/thermometre.jpg", alt: "Thermomètre", width: 1200, height: 900, blurDataURL: blurPlaceholder }],
    location: moncoutant,
    faq: [{ question: "Plage de température ?", answer: "-50°C à +300°C." }],
  },
  {
    slug: "housse-protection-brasero",
    name: "Housse Protection Braséro",
    category: "accessoire",
    price: 59,
    shortDescription: "Housse imperméable toutes tailles.",
    description: "Housse en polyester enduit PVC, imperméable et résistante aux UV. Élastique de serrage et sangles de fixation.",
    madeIn: "France",
    material: "Polyester PVC",
    diameter: 90,
    thickness: 0,
    height: 50,
    weight: 0.8,
    warranty: "Garantie 2 ans",
    availability: "En stock",
    shipping: "Livraison sous 2 jours",
    popularScore: 78,
    badge: "Protection",
    specs: { acier: "N/A", epaisseur: "N/A", dimensions: "Ø90 x H50 cm", poids: "0.8 kg" },
    highlights: ["Imperméable", "Anti-UV", "Élastique serrage"],
    features: [{ icon: "ShieldCheck", title: "Tout temps", description: "Protection 4 saisons." }],
    images: [{ src: "/accessories/housse-protection.jpg", alt: "Housse braséro", width: 1200, height: 900, blurDataURL: blurPlaceholder }],
    location: moncoutant,
    faq: [{ question: "Quelles tailles ?", answer: "Convient aux braséros jusqu'à 90 cm." }],
  },
  {
    slug: "anneau-plancha-95",
    name: "Anneau Plancha Ø95 cm",
    category: "accessoire",
    price: 329,
    shortDescription: "Anneau plancha XL pour braséro 95-100 cm.",
    description:
      "Anneau plancha en acier corten de 8 mm pensé pour les braséros XXL. Gouttière périphérique et perçages pour évacuer les jus, poignées soudées pour un positionnement facile.",
    madeIn: "France",
    material: "Acier corten",
    diameter: 95,
    thickness: 8,
    height: 5,
    weight: 18,
    warranty: "Garantie 3 ans",
    availability: "Sur commande",
    shipping: "Livraison sous 10 jours",
    popularScore: 88,
    badge: "Gastronomie",
    specs: { acier: "Corten 8 mm", epaisseur: "8 mm", dimensions: "Ø 95 cm", poids: "18 kg" },
    highlights: ["Surface XL", "Rigole anti-jus", "Poignées soudées"],
    features: [
      { icon: "Flame", title: "Cuisson uniforme", description: "Masse épaisse garantissant une inertie parfaite." },
      { icon: "Droplet", title: "Rigole intégrée", description: "Canalise les jus de cuisson vers un point de collecte." },
    ],
    images: [
      {
        src: "https://images.unsplash.com/photo-1470337458703-46ad1756a187?auto=format&fit=crop&w=1200&q=80",
        alt: "Anneau plancha corten",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
    ],
    location: moncoutant,
    faq: [{ question: "Compatible avec quel modèle ?", answer: "Tous nos braséros de 95 à 100 cm de diamètre." }],
  },
  {
    slug: "kit-cuisson-pizza",
    name: "Kit Cuisson Pizza Braséro",
    category: "accessoire",
    price: 259,
    shortDescription: "Cloche inox et pierre réfractaire pour pizzas au braséro.",
    description:
      "Cloche en inox 304 perforée et pierre réfractaire 33 cm pour transformer votre braséro en four à pizza. Thermomètre intégré pour maîtriser la cuisson.",
    madeIn: "France",
    material: "Inox / Pierre",
    diameter: 45,
    thickness: 4,
    height: 32,
    weight: 7,
    warranty: "Garantie 2 ans",
    availability: "En stock",
    shipping: "Livraison sous 4 jours",
    popularScore: 85,
    badge: "Street-food",
    specs: { acier: "Inox 304", epaisseur: "4 mm", dimensions: "Cloche Ø45 cm", poids: "7 kg" },
    highlights: ["Thermomètre intégré", "Pierre réfractaire", "Poignée isolée"],
    features: [
      { icon: "ChefHat", title: "Pizza maison", description: "Cuisson à 400°C grâce à la cloche inox ventilée." },
      { icon: "Thermometer", title: "Température contrôlée", description: "Suivi précis de la chaleur en façade." },
    ],
    images: [
      {
        src: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=1200&q=80",
        alt: "Kit pizza pour braséro",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
    ],
    location: moncoutant,
    faq: [{ question: "Temps de chauffe ?", answer: "Préchauffez 15 minutes avant d'enfourner la première pizza." }],
  },
  {
    slug: "plateau-service-chene",
    name: "Plateau Service Chêne",
    category: "accessoire",
    price: 69,
    shortDescription: "Plateau en chêne huilé assorti aux braséros.",
    description:
      "Plateau de service en chêne massif issu de forêts françaises gérées durablement. Rainures anti-égouttement et poignées fraisées.",
    madeIn: "France",
    material: "Chêne massif",
    diameter: 0,
    thickness: 2,
    height: 4,
    weight: 1.8,
    warranty: "Garantie 2 ans",
    availability: "En stock",
    shipping: "Livraison sous 3 jours",
    popularScore: 73,
    badge: "Artisanat",
    specs: { acier: "N/A", epaisseur: "2 cm", dimensions: "45 x 30 cm", poids: "1.8 kg" },
    highlights: ["Bois PEFC", "Rainures anti-jus", "Poignées intégrées"],
    features: [
      { icon: "Leaf", title: "Durable", description: "Chêne certifié PEFC et finition huile naturelle." },
      { icon: "Hand", title: "Confort", description: "Poignées fraisées pour un service sûr." },
    ],
    images: [
      {
        src: "https://images.unsplash.com/photo-1504753793650-d4a2b783c15f?auto=format&fit=crop&w=1200&q=80",
        alt: "Plateau en chêne",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
    ],
    location: moncoutant,
    faq: [{ question: "Entretien ?", answer: "Essuyer après usage, re-huiler tous les 6 mois." }],
  },
  {
    slug: "module-preparation-inox",
    name: "Module Préparation Inox",
    category: "accessoire",
    price: 420,
    shortDescription: "Plan de travail inox sur pieds réglables.",
    description:
      "Module de préparation en inox brossé assorti à votre braséro. Plateau 90x50 cm, tablette basse pour stocker les accessoires et pieds réglables pour terrain irrégulier.",
    madeIn: "France",
    material: "Inox 304",
    diameter: 0,
    thickness: 2,
    height: 90,
    weight: 28,
    warranty: "Garantie 5 ans",
    availability: "Sur commande",
    shipping: "Livraison sous 12 jours",
    popularScore: 80,
    badge: "Atelier",
    specs: { acier: "Inox 304", epaisseur: "2 mm", dimensions: "90 x 50 x 90 cm", poids: "28 kg" },
    highlights: ["Pieds réglables", "Tablette basse", "Inox alimentaire"],
    features: [
      { icon: "Ruler", title: "Stable", description: "Réglage précis pour s'adapter à toutes les terrasses." },
      { icon: "Box", title: "Rangement bas", description: "Tablette inférieure pour stocker planchas et outils." },
    ],
    images: [
      {
        src: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=1200&q=80",
        alt: "Module inox extérieur",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
    ],
    location: moncoutant,
    faq: [{ question: "Résiste à la pluie ?", answer: "Oui, inox 304 résistant à la corrosion." }],
  },
  {
    slug: "panier-grillades-inox",
    name: "Panier Grillades Inox",
    category: "accessoire",
    price: 59,
    shortDescription: "Panier de cuisson pour légumes ou poissons.",
    description:
      "Panier en maille inox à poser sur grille ou plancha. Les parois hautes empêchent les aliments de tomber dans le feu et assurent une cuisson homogène.",
    madeIn: "France",
    material: "Inox 304",
    diameter: 0,
    thickness: 0,
    height: 9,
    weight: 1.1,
    warranty: "Garantie 3 ans",
    availability: "En stock",
    shipping: "Livraison sous 2 jours",
    popularScore: 77,
    badge: "Cuisine",
    specs: { acier: "Inox 304", epaisseur: "Maille 1.5 mm", dimensions: "30 x 25 x 9 cm", poids: "1.1 kg" },
    highlights: ["Inox perforé", "Poignées repliables", "Passe lave-vaisselle"],
    features: [
      { icon: "ChefHat", title: "Multi-cuissons", description: "Légumes, poissons ou châtaignes sans perte." },
    ],
    images: [
      {
        src: "https://images.unsplash.com/photo-1432139509613-5c4255815697?auto=format&fit=crop&w=1200&q=80",
        alt: "Panier grillades",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
    ],
    location: moncoutant,
    faq: [{ question: "Passe-t-il au lave-vaisselle ?", answer: "Oui, l'inox 304 supporte les lavages répétés." }],
  },
  {
    slug: "set-brochettes-gourmet",
    name: "Set 8 Brochettes Gourmet",
    category: "accessoire",
    price: 54,
    shortDescription: "Brochettes plates anti-rotation en inox.",
    description:
      "Lot de 8 brochettes en inox brossé avec butée coulissante. Section plate pour éviter que les aliments tournent à la cuisson et paires identifiées par couleur.",
    madeIn: "France",
    material: "Inox 304",
    diameter: 0,
    thickness: 2,
    height: 45,
    weight: 0.7,
    warranty: "Garantie 3 ans",
    availability: "En stock",
    shipping: "Livraison sous 2 jours",
    popularScore: 81,
    badge: "Gourmet",
    specs: { acier: "Inox 304", epaisseur: "2 mm", dimensions: "L 45 cm", poids: "0.7 kg (set)" },
    highlights: ["Butées réglables", "Section plate", "Repères couleur"],
    features: [
      { icon: "Utensils", title: "Service rapide", description: "Repères colorés pour différencier les cuissons." },
    ],
    images: [
      {
        src: "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1200&q=80",
        alt: "Brochettes inox",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
    ],
    location: moncoutant,
    faq: [{ question: "Peut-on les poser sur plancha ?", answer: "Oui, elles supportent plus de 600°C." }],
  },
  {
    slug: "kit-nettoyage-premium",
    name: "Kit Nettoyage Premium",
    category: "accessoire",
    price: 75,
    shortDescription: "Trousse complète pour entretenir votre braséro.",
    description:
      "Comprend une brosse laiton, un grattoir inox, un chiffon microfibre et une huile protectrice. Livré dans une trousse en toile cirée.",
    madeIn: "France",
    material: "Inox / Bois / Toile",
    diameter: 0,
    thickness: 0,
    height: 0,
    weight: 1.2,
    warranty: "Garantie 1 an",
    availability: "En stock",
    shipping: "Livraison sous 2 jours",
    popularScore: 79,
    badge: "Entretien",
    specs: { acier: "Inox + laiton", epaisseur: "N/A", dimensions: "Trousse 35 x 15 cm", poids: "1.2 kg" },
    highlights: ["Trousse incluse", "Huile protectrice", "Brosse laiton"],
    features: [
      { icon: "Sparkles", title: "Braséro impeccable", description: "Tous les outils indispensables réunis." },
      { icon: "Droplet", title: "Huile protectrice", description: "Protège l'acier corten après nettoyage." },
    ],
    images: [
      {
        src: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=1200&q=80",
        alt: "Kit nettoyage braséro",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
    ],
    location: moncoutant,
    faq: [{ question: "Combien d'huiles fournies ?", answer: "Un flacon de 200 ml, soit 8 applications complètes." }],
  },
  {
    slug: "chariot-service-bois",
    name: "Chariot Service Bois",
    category: "accessoire",
    price: 590,
    shortDescription: "Chariot mobile pour servir et stocker le bois.",
    description:
      "Chariot en acier corten et plateau chêne, équipé de grosses roues gonflables. Permet de transporter les bûches, poser les assiettes et déplacer les accessoires.",
    madeIn: "France",
    material: "Acier corten / Chêne",
    diameter: 0,
    thickness: 3,
    height: 95,
    weight: 38,
    warranty: "Garantie 5 ans",
    availability: "Sur commande",
    shipping: "Livraison sous 14 jours",
    popularScore: 83,
    badge: "Mobilité",
    specs: { acier: "Corten 3 mm", epaisseur: "3 mm", dimensions: "110 x 50 x 95 cm", poids: "38 kg" },
    highlights: ["Roue gonflable", "Plateau chêne", "Grande capacité"],
    features: [
      { icon: "Truck", title: "Ultra mobile", description: "Roues Ø30 cm pour franchir gravillons et pelouse." },
      { icon: "Box", title: "Double plateau", description: "Plan de travail haut et casier à bûches bas." },
    ],
    images: [
      {
        src: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1200&q=80",
        alt: "Chariot de service extérieur",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
    ],
    location: moncoutant,
    faq: [{ question: "Livré monté ?", answer: "Oui, seul le plateau chêne reste à fixer (2 vis)." }],
  },
  {
    slug: "lampe-led-aimantee",
    name: "Lampe LED Aimantée",
    category: "accessoire",
    price: 69,
    shortDescription: "Lampe rechargeable aimantée pour éclairer la zone cuisson.",
    description:
      "Lampe LED rechargeable USB-C avec base aimantée orientable. Trois intensités lumineuses pour sécuriser vos cuissons nocturnes.",
    madeIn: "France",
    material: "Aluminium anodisé",
    diameter: 0,
    thickness: 0,
    height: 28,
    weight: 0.6,
    warranty: "Garantie 2 ans",
    availability: "En stock",
    shipping: "Livraison sous 3 jours",
    popularScore: 74,
    badge: "Sécurité",
    specs: { acier: "Aluminium", epaisseur: "N/A", dimensions: "L 28 cm", poids: "0.6 kg" },
    highlights: ["USB-C", "Aimant puissant", "3 intensités"],
    features: [
      { icon: "Lightbulb", title: "Éclairage ciblé", description: "Bras flexible pour orienter la lumière sur la plancha." },
      { icon: "Battery", title: "Autonomie 10h", description: "Recharge complète en 90 minutes." },
    ],
    images: [
      {
        src: "https://images.unsplash.com/photo-1481277542470-605612bd2d61?auto=format&fit=crop&w=1200&q=80",
        alt: "Lampe LED extérieure",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
    ],
    location: moncoutant,
    faq: [{ question: "Supporte la chaleur ?", answer: "Oui, protégée jusqu'à 120°C autour du braséro." }],
  },
  {
    slug: "sac-rangement-accessoires",
    name: "Sac Rangement Accessoires",
    category: "accessoire",
    price: 85,
    shortDescription: "Grand sac en toile cirée pour transporter vos équipements.",
    description:
      "Sac de transport 70 litres en toile cirée résistante, doublé d'une mousse protectrice. Compartiments internes modulables pour ranger pinces, planchas ou gants.",
    madeIn: "France",
    material: "Toile cirée / Cuir",
    diameter: 0,
    thickness: 0,
    height: 40,
    weight: 2.3,
    warranty: "Garantie 2 ans",
    availability: "En stock",
    shipping: "Livraison sous 4 jours",
    popularScore: 76,
    badge: "Transport",
    specs: { acier: "N/A", epaisseur: "Toile 1.2 mm", dimensions: "70 x 35 x 40 cm", poids: "2.3 kg" },
    highlights: ["70 L", "Intérieur modulable", "Bandoulière cuir"],
    features: [
      { icon: "Briefcase", title: "Tout emporter", description: "Compartiments réglables par velcro." },
      { icon: "ShieldCheck", title: "Protection", description: "Fond renforcé et mousse protectrice." },
    ],
    images: [
      {
        src: "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=80",
        alt: "Sac de transport accessoires",
        width: 1200,
        height: 900,
        blurDataURL: blurPlaceholder,
      },
    ],
    location: moncoutant,
    faq: [{ question: "Nettoyage ?", answer: "Éponge humide, pas de machine. Le cuir se nourrit avec un lait incolore." }],
  },
];

export const products = rawProducts.map((product) => productSchema.parse(product));

export const braseros = products.filter((product) => product.category === "brasero");

export const accessoires = products.filter((product) => product.category === "accessoire");

export const featuredProduct = products.find((product) => product.slug === "brasero-signature-80")!;
